version: "3.7"

services:
  db:
    image: ghcr.io/getzep/postgres:latest
    restart: on-failure
    shm_size: "128mb"
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    expose:
      - 5432
    networks:
      - zep-network
    volumes:
      - zep-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "$SERVICE_USER_POSTGRES"]
      interval: 5s
      timeout: 5s
      retries: 5

  nlp:
    image: ghcr.io/getzep/zep-nlp-server:latest
    restart: on-failure
    expose:
      - 5557
    networks:
      - zep-network
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5557' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s

  zep:
    image: ghcr.io/getzep/zep:latest
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      nlp:
        condition: service_healthy
    expose:
      - 8000
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - ZEP_STORE_POSTGRES_DSN=postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@$SERVICE_INTERNAL_URL_DB/postgres?sslmode=disable
      - ZEP_NLP_SERVER_URL=http://nlp:5557
      - ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_SERVICE=$SERVICE_EXTRACTORS_DOCUMENTS_EMBEDDINGS_SERVICE
      - ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_DIMENSIONS=$SERVICE_EXTRACTORS_DOCUMENTS_EMBEDDINGS_DIMENSIONS
      - ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_SERVICE=$SERVICE_EXTRACTORS_MESSAGES_EMBEDDINGS_SERVICE
      - ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_DIMENSIONS=$SERVICE_EXTRACTORS_MESSAGES_EMBEDDINGS_DIMENSIONS
      - ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_SERVICE=$SERVICE_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_SERVICE
      - ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_DIMENSIONS=$SERVICE_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_DIMENSIONS
      - ZEP_OPENAI_API_KEY=$SERVICE_OPENAI_API_KEY
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8000' || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zep-network

networks:
  zep-network:
    name: coolify
    external: true

volumes:
  zep-db:
